### ISSUE TITLE
improve permalinks icon

### ISSUE THREAD

**Issue by fredmaggiowski** [rond-authz/rond-authz.github.io#43]
The permalink icon opens up only when hovering with the mouse in the correct spot and has a weird appearance confronted with the rest of the page, for sure it can be improved

<img width="402" alt="image(2)" src="https://user-images.githubusercontent.com/7142570/183641952-075d4b29-b9a3-4187-b363-d08cc1ed7aa2.png">

**Comment by Massibian** [comment]
#45
